terraform {
  required_version = "~> 1.16.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 5.6"
    }
  }

  # Partial configuration: storage_account_name and container_name come from
  # backend.hcl (generated by azure/bootstrap, gitignored).
  #   terraform init -backend-config=backend.hcl
  # Locking is a native blob lease on the state blob.
  backend "azurerm" {
    key = "envs/dev/terraform.tfstate"
    # Entra ID auth with your az login. The state account has Shared Key
    # disabled, so key-based access isn't an option.
    use_azuread_auth = true
  }
}

provider "azurerm" {
  # Pinned so a plan can never land in whichever subscription `az account set`
  # selected last.
  subscription_id = var.subscription_id

  # azurerm 5.0 registers no Resource Providers by default. Network for the
  # VNets and NSGs; PolicyInsights so policy compliance results are recorded;
  # the rest for the optional AKS spoke (enable_aks).
  resource_providers_to_register = [
    "Microsoft.Network",
    "Microsoft.PolicyInsights",
    "Microsoft.ContainerService",
    "Microsoft.ContainerRegistry",
    "Microsoft.ManagedIdentity",
    "Microsoft.Compute",
  ]

  features {}
}
